version: "3.9"
services:
  worker:
    build: .
    environment:
      API_ID: $API_ID
      API_HASH: $API_HASH
      DATABASE_URL: $DATABASE_URL
      CHANNELS: $CHANNELS
      DATABASE_NAME: $DATABASE_NAME
